/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Fira Code', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            maxWidth: '65ch',
            color: theme('colors.gray.800'),
            lineHeight: '1.75',
            fontSize: '1.125rem',
            '--tw-prose-body': theme('colors.gray.800'),
            '--tw-prose-headings': theme('colors.gray.900'),
            '--tw-prose-lead': theme('colors.gray.700'),
            '--tw-prose-links': theme('colors.blue.600'),
            '--tw-prose-bold': theme('colors.gray.900'),
            '--tw-prose-counters': theme('colors.gray.600'),
            '--tw-prose-bullets': theme('colors.gray.400'),
            '--tw-prose-hr': theme('colors.gray.300'),
            '--tw-prose-quotes': theme('colors.gray.900'),
            '--tw-prose-quote-borders': theme('colors.blue.500'),
            '--tw-prose-captions': theme('colors.gray.700'),
            '--tw-prose-code': theme('colors.gray.900'),
            '--tw-prose-pre-code': theme('colors.gray.100'),
            '--tw-prose-pre-bg': theme('colors.gray.900'),
            '--tw-prose-th-borders': theme('colors.gray.300'),
            '--tw-prose-td-borders': theme('colors.gray.200'),
            h1: {
              fontSize: '2.5rem',
              fontWeight: '800',
              lineHeight: '1.2',
              marginTop: '0',
              marginBottom: '1.5rem',
              letterSpacing: '-0.02em',
            },
            h2: {
              fontSize: '2rem',
              fontWeight: '700',
              lineHeight: '1.3',
              marginTop: '2.5rem',
              marginBottom: '1.25rem',
              letterSpacing: '-0.01em',
            },
            h3: {
              fontSize: '1.5rem',
              fontWeight: '600',
              lineHeight: '1.4',
              marginTop: '2rem',
              marginBottom: '1rem',
            },
            h4: {
              fontSize: '1.25rem',
              fontWeight: '600',
              lineHeight: '1.5',
              marginTop: '1.5rem',
              marginBottom: '0.75rem',
            },
            p: {
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              fontSize: '1.125rem',
              lineHeight: '1.75',
            },
            'p:first-of-type': {
              fontSize: '1.25rem',
              lineHeight: '1.7',
              color: theme('colors.gray.700'),
            },
            a: {
              color: theme('colors.blue.600'),
              textDecoration: 'none',
              fontWeight: '500',
              borderBottom: '1px solid',
              borderColor: theme('colors.blue.300'),
              transition: 'all 0.2s',
              '&:hover': {
                color: theme('colors.blue.700'),
                borderColor: theme('colors.blue.600'),
              },
            },
            strong: {
              fontWeight: '600',
              color: theme('colors.gray.900'),
            },
            ul: {
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              paddingLeft: '1.5rem',
            },
            ol: {
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              paddingLeft: '1.5rem',
            },
            li: {
              marginTop: '0.75rem',
              marginBottom: '0.75rem',
              paddingLeft: '0.5rem',
              fontSize: '1.125rem',
              lineHeight: '1.75',
            },
            'li::marker': {
              color: theme('colors.gray.500'),
              fontWeight: '500',
            },
            blockquote: {
              fontStyle: 'italic',
              fontSize: '1.25rem',
              lineHeight: '1.6',
              paddingLeft: '1.5rem',
              borderLeftWidth: '4px',
              borderLeftColor: theme('colors.blue.500'),
              marginTop: '2rem',
              marginBottom: '2rem',
              color: theme('colors.gray.700'),
              fontWeight: '400',
              quotes: '"\\201C""\\201D""\\2018""\\2019"',
            },
            'blockquote p:first-of-type::before': {
              content: 'open-quote',
            },
            'blockquote p:last-of-type::after': {
              content: 'close-quote',
            },
            code: {
              backgroundColor: theme('colors.gray.100'),
              color: theme('colors.gray.900'),
              fontWeight: '500',
              fontSize: '0.875em',
              padding: '0.25rem 0.375rem',
              borderRadius: '0.25rem',
              fontFamily: theme('fontFamily.mono').join(', '),
            },
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            pre: {
              backgroundColor: theme('colors.gray.900'),
              color: theme('colors.gray.100'),
              fontSize: '0.875rem',
              lineHeight: '1.7',
              marginTop: '2rem',
              marginBottom: '2rem',
              borderRadius: '0.5rem',
              padding: '1.25rem 1.5rem',
              overflowX: 'auto',
            },
            'pre code': {
              backgroundColor: 'transparent',
              borderWidth: '0',
              borderRadius: '0',
              padding: '0',
              fontWeight: '400',
              color: 'inherit',
              fontSize: 'inherit',
              fontFamily: 'inherit',
              lineHeight: 'inherit',
            },
            table: {
              width: '100%',
              marginTop: '2rem',
              marginBottom: '2rem',
              fontSize: '0.95rem',
            },
            thead: {
              borderBottomWidth: '2px',
              borderBottomColor: theme('colors.gray.300'),
            },
            'thead th': {
              fontWeight: '600',
              paddingBottom: '0.75rem',
            },
            'tbody tr': {
              borderBottomWidth: '1px',
              borderBottomColor: theme('colors.gray.200'),
            },
            'tbody td': {
              paddingTop: '0.75rem',
              paddingBottom: '0.75rem',
            },
            hr: {
              borderColor: theme('colors.gray.200'),
              marginTop: '3rem',
              marginBottom: '3rem',
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};
